
export const mockModels = [
  {
    id: 'llama-2-7b',
    name: 'Llama 2 7B',
    subtitle: 'by Meta AI',
    description: 'A collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters.',
    rating: 4.5,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Open Source'],
    industries: ['Technology', 'Finance'],
    deploymentOptions: ['Cloud', 'On-Premise'],
    inferenceTasks: ['Text Generation', 'Translation'],
    fineTuningTasks: ['Classification', 'Summarization'],
    version: '2.0',
    objective: 'Large language model designed for general-purpose text generation and understanding tasks.',
    stats: { projects: 42, pipelines: 15, activeDeployments: 8 },
    availableVersions: ['1.0', '2.0', '2.1']
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    subtitle: 'by OpenAI',
    description: 'Most capable GPT-3.5 model and optimized for chat at 1/10th the cost of text-davinci-003.',
    rating: 4.8,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Enterprise'],
    industries: ['Technology', 'Healthcare', 'Finance'],
    deploymentOptions: ['Cloud'],
    inferenceTasks: ['Text Generation', 'Translation'],
    fineTuningTasks: ['Classification', 'Sentiment Analysis'],
    version: '0613',
    objective: 'Optimized for conversational AI and instruction-following tasks.',
    stats: { projects: 128, pipelines: 45, activeDeployments: 23 },
    availableVersions: ['0301', '0613', '1106']
  },
  {
    id: 'claude-2',
    name: 'Claude 2',
    subtitle: 'by Anthropic',
    description: 'Claude 2 is a next-generation AI assistant based on Anthropics research into training helpful, harmless, and honest AI systems.',
    rating: 4.6,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Enterprise'],
    industries: ['Technology', 'Healthcare'],
    deploymentOptions: ['Cloud', 'Hybrid'],
    inferenceTasks: ['Text Generation', 'Translation'],
    fineTuningTasks: ['Classification', 'Summarization'],
    version: '2.0',
    objective: 'Constitutional AI model designed for safety and helpfulness.',
    stats: { projects: 67, pipelines: 22, activeDeployments: 12 },
    availableVersions: ['1.0', '2.0']
  },
  {
    id: 'stable-diffusion-xl',
    name: 'Stable Diffusion XL',
    subtitle: 'by Stability AI',
    description: 'Most advanced flagship image model with stunning visuals and composition. Generate high-quality images with shorter prompts.',
    rating: 4.4,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Open Source'],
    industries: ['Technology', 'Retail'],
    deploymentOptions: ['Cloud', 'On-Premise', 'Edge'],
    inferenceTasks: ['Image Recognition'],
    fineTuningTasks: ['Classification'],
    version: '1.0',
    objective: 'Advanced text-to-image generation with improved quality and composition.',
    stats: { projects: 89, pipelines: 31, activeDeployments: 19 },
    availableVersions: ['0.9', '1.0']
  },
  {
    id: 'whisper-large',
    name: 'Whisper Large',
    subtitle: 'by OpenAI',
    description: 'Robust speech recognition model trained on 680,000 hours of multilingual and multitask supervised data.',
    rating: 4.7,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Open Source'],
    industries: ['Technology', 'Healthcare'],
    deploymentOptions: ['Cloud', 'On-Premise'],
    inferenceTasks: ['Speech-to-Text'],
    fineTuningTasks: ['Named Entity Recognition'],
    version: 'v3',
    objective: 'Multilingual automatic speech recognition and speech translation.',
    stats: { projects: 34, pipelines: 18, activeDeployments: 9 },
    availableVersions: ['v2', 'v3']
  },
  {
    id: 'bert-large',
    name: 'BERT Large',
    subtitle: 'by Google',
    description: 'Bidirectional Encoder Representations from Transformers - a method of pre-training language representations.',
    rating: 4.3,
    imageUrl: '/placeholder.svg',
    collections: ['Foundation Models', 'Open Source'],
    industries: ['Technology', 'Finance'],
    deploymentOptions: ['Cloud', 'On-Premise'],
    inferenceTasks: ['Text Generation'],
    fineTuningTasks: ['Classification', 'Named Entity Recognition', 'Sentiment Analysis'],
    version: '1.0',
    objective: 'Bidirectional language understanding for various NLP tasks.',
    stats: { projects: 156, pipelines: 72, activeDeployments: 34 },
    availableVersions: ['1.0']
  }
];

export const getModelById = (id: string) => {
  return mockModels.find(model => model.id === id);
};
